### ISSUE TITLE
support calling function after comparison

### ISSUE THREAD

**Issue by chenenze** [huttotw/grules#14]
hi, grules can grules be extended and compared to call functions? This will complete my function after comparison

**Comment by huttotw** [comment]
@chenenze sorry for the late response.

I'm not sure exactly what you mean. Could you give a sample piece of code to illustrate the desired API? Or perhaps a more detailed use case?

**Comment by huttotw** [comment]
@chenenze if you are looking to use a custom function in order to do the comparison, you can register a custom function by doing something like this:

```go
e, err := grules.NewJSONEngine(...)
if err != nil {
    panic(err)
}

e = e.AddComparator("my-custom-location-comparator", func(a, b interface{}) bool {
    user1 := a.(mypackage.User)
    userB := b.(mypackage.User)

    if user1.CurrentLocation() == user2.CurrentLocation() {
        return true
    }

    return false
})
```
