### ISSUE TITLE
Support for []interface{}

### ISSUE THREAD

**Issue by ddouglas** [huttotw/grules#16]
Hello,

I work with Thomas @ RV and stumbled upon his old go-rules lib. After forking it and rewriting a bit of it to fix some bugs and support `[]interfaces{}`, he pointed me to you because your lib supports ORs. I didn't directly see it, but do you support arrays as well?

Use case is this. I have the following object that gets passed to my application
_Using a collapse here since it is a large JSON Object_
<details>
<p>

```json
{
   "attackers":[
      {
         "alliance_id":933731581,
         "character_id":497009078,
         "corporation_id":1975749457,
         "damage_done":441,
         "final_blow":true,
         "security_status":0.6,
         "ship_type_id":12013,
         "weapon_type_id":2913
      },
      {
         "alliance_id":933731581,
         "character_id":2114053773,
         "corporation_id":1975749457,
         "damage_done":19,
         "final_blow":false,
         "security_status":-3.4,
         "ship_type_id":17932,
         "weapon_type_id":2488
      }
   ],
   "killmail_id":88355893,
   "killmail_time":"2020-11-03T03:46:15Z",
   "solar_system_id":30004044,
   "victim":{
      "character_id":95525506,
      "corporation_id":1000169,
      "damage_taken":460,
      "items":[
         {
            "flag":89,
            "item_type_id":19689,
            "quantity_destroyed":1,
            "singleton":0
         },
         {
            "flag":89,
            "item_type_id":10221,
            "quantity_destroyed":1,
            "singleton":0
         },
         {
            "flag":89,
            "item_type_id":10225,
            "quantity_destroyed":1,
            "singleton":0
         },
         {
            "flag":89,
            "item_type_id":10208,
            "quantity_destroyed":1,
            "singleton":0
         },
         {
            "flag":89,
            "item_type_id":10212,
            "quantity_destroyed":1,
            "singleton":0
         },
         {
            "flag":89,
            "item_type_id":10216,
            "quantity_destroyed":1,
            "singleton":0
         }
      ],
      "position":{
         "x":1885476739647.2476,
         "y":-289004063236.799,
         "z":-1406745348275.7405
      },
      "ship_type_id":670
   }
}
```

</p>
</details>

I need to be able to potentially write rules against the `attackers` array of objects and/or the `victim.items` array of objects.

My solution for the fork of  Thomas's lib was to return a `[]interface` from pluck. If in pluck the type  of the key is of type `map[string]interface{}{}` then, append to a slice of interface and move on, if it is of type `[]interface{}` recursively call the pluck method on each object in the array.

Was wondering what the lift would be and if you could make the change to support arrays or would you expect a PR if I did it myself.

For reference here is my fork: https://github.com/eveisesi/zrule/blob/main/pkg/ruler/ruler.go

_I was having problems with go.mod and creating a work package so it is currently embedded in the application I forked and modified it for_

As you can see here: https://github.com/eveisesi/zrule/blob/main/pkg/ruler/ruler.go#L97, I do what I stated above.

PS. I haven't read all of you code yet, I just noticed that your pluck function look eerily familiar to Thomas's.

**Comment by huttotw** [comment]
@ddouglas sorry for the super-delayed response.

I think the easiest solution for your problem would be to loop through `attackers` yourself and run the rules on each one. Theoretically, it would be as fast, if not faster than anything Grules could do. Maybe this library can help you with plucking your array before feeding it to Grules:

https://github.com/Jeffail/gabs

**Comment by ddouglas** [comment]
Yeah, the application I was going to use this for was a pet project that didn't go anywhere. Thank you for responding though.
